name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This fixes the exit code 128 error!
    
    steps:
      - name: Generate Snake Game from GitHub Contribution Graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Fardeen37
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4 # Updated to v4 to fix the warning!
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
